### PR TITLE
patch systray

### PR DESCRIPTION
**Pull request by codeitlikemiley**

### CODE REVIEW

**Comment by codeitlikemiley** [comment]
@LukeSmithxyz  Ive patch it please check ive added only what is needed i remove my custom keybindings

**Comment by codeitlikemiley** [comment]
Im using this patch now heres a pic of other system tray im using after dwmblocks
3 custom icons of other apps are shown in the pics
pic-full-200417-2224-54

**Comment by codeitlikemiley** [comment]
that diff file i added is from the official dwm page...
Yes it will not work by issuing a patch command, thats why I create this Pull request 
because i manually patch each lines that needs to be changed

**Comment by AlexSyssoyev** [comment]
I think the system tray is overdoing it. In my honest opinion, I don't need it and I can't really see any situation where it is indispensable to use it.

Edit: Actually as I think about it, there is nothing that can't be done using dwmblocks instead of bloating with a systray

**Pull request closed without merging**
