### PR TITLE
Bump to version 6.4

### PR DESCRIPTION
**Pull request by iStagnant**
I was bumping my build of [dwm](https://github.com/iStagnant/dwmrice/tree/master/.config/dwm) and thought to try the diff file on your build, and not many rejects occurred so i fixed all of them manually, i also saw that you have already applied some patches from after version 6.2, the only reject i couldn't solve was one related to the `tile` function which was not existing in your `dwm.c` i think it was replaced by the patch that added multiple layouts.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
I notice that `lockfullscreen` is preventing full screen windows from being closed, which I don't this is the purpose. I had added a patch before that prevented moving from the focused window, and I think they might be interfering. Might check later.

**Comment by iStagnant** [comment]
Indeed the commit was added to main dwm by the guy that made the patch you're talking about, and later someone added the `lockfullscreen` variable to turn it on or off, if it's the thing causing problems i can remove it.

**Comment by LukeSmithxyz** [comment]
I'd rather remove the unique version my build has and replace it with the upstream one with the variable.

**Comment by iStagnant** [comment]
I'll work on removing the patch after a couple of hours when i have time.

**Comment by iStagnant** [comment]
I fixed the issue the patch seemed to have been applied to `killclient` instead of `focusstack` you probably shouldn't merge this since a mistake like that happened tomorrow i'll redo the patching and confirm every patch was applied where it should be.

**Pull request closed without merging**
